chef/chefstyle

config/chefstyle.yml
we get these for free with no work.
=> enable lint checks that already pass

config/chefstyle.yml
these two are disabled because of strong negative feels from chef/chef
maintainers.
=> document cops we decided to disable

config/chefstyle.yml
they are highly annoying and very time consuming to fix
=> disable all the metrics cops

config/chefstyle.yml
chef/chef master should currently pass
=> these cops have been fixed in chef/chef

config/chefstyle.yml
already merged the chef/chef PRs for these
=> more cops fixed in chef/chef

config/chefstyle.yml
no offenses to fix on any of these in chef/chef
=> cops that we can Enable for free

config/chefstyle.yml
https://github.com/chef/chef/pull/4526
=> fixed in chef/chef already

config/chefstyle.yml
this goes along with https://github.com/chef/chef/pull/4541
validated that after installing these changes that chef/chef
master is still clean.
=> yet more cops

config/chefstyle.yml, config/disable_all.yml, config/disabled.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
also changing the enforcement style of MultilineOperationIndentation
see:
https://github.com/chef/chef/pull/4573
=> bumping rubocop

config/disable_all.yml, config/disabled.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
Bump Rubocop to 0.39.0 to pick up parser bug fixes.
=> Rubocop 0.39.0

config/chefstyle.yml
pending https://github.com/chef/chef/pull/5196 merged
=> add more cops

config/chefstyle.yml
=> disabling ternaryparenthesis

config/chefstyle.yml
=> this gets kind of annoying when upgrading rulesets

config/chefstyle.yml
=> fix my typo

config/disable_all.yml, config/disabled.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
doesn't add any new rules, just bumps the engine.   engine does have a couple tweaks that affects rules in chef/chef.
=> rubocop 0.44.1 upgrade

config/disable_all.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
this seems to be a no-op for chef/chef
=> bump rubocop engine to 0.45.0

config/chefstyle.yml
=> enable Lint/UnifiedInteger cop

config/chefstyle.yml
new cops added that have no violations in chef/chef, cops that we need
to disable, etc.
=> cops settings that don't require chef/chef changes

config/chefstyle.yml
this is the companion PR to https://github.com/chef/chef/pull/5548
=> more cop updates

config/chefstyle.yml
=> more tweaks to chefstyle

config/chefstyle.yml, config/disable_all.yml, config/disabled.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
chef/chef#5798 has the only update needed to chef/chef for this release
=> rubocop engine upgrade to 0.47.1

.travis.yml, README.md, Rakefile, chefstyle.gemspec
This brings chefstyle inline with our other projects.
=> Require at least Ruby 2.2

config/chefstyle.yml
in some cases this catches typos, in other cases its new cops
that we have no offenses for in chef/chef
=> add some no-offenses cops

config/chefstyle.yml
Otherwise we get weird failures on appveyor
=> enforce LF everywhere

config/chefstyle.yml
=> fix the eol cop config

config/chefstyle.yml, config/disable_all.yml, config/disabled.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
🚧  blocked on Chef-DK 3 / Chef 14 🚧
=> bump rubocop engine to 0.52.1

config/disable_all.yml, config/enabled.yml, config/upstream.yml, lib/chefstyle/version.rb
This lets us bring 0.55 into Chefstyle and ship that in DK 3
=> Release 0.10.0 with Rubocop 0.55.0

config/chefstyle.yml
see chef/chef#7414, chef/chef#7415, chef/chef#7417
=> enabling another batch of cops

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, chefstyle.gemspec
This breaks installs on systems with bundler 2.x
=> Unpin the bundler dev dep

config/chefstyle.yml
See discussion in https://github.com/chef/chef/pull/8787
=> turn off block delimiters, allow semantic style

config/chefstyle.yml, config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
This matches the version we'll be updating to in Cookstyle
=> Update the RuboCop engine to 0.80.1

.expeditor/config.yml, .expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
Test on Windows and Ruby 2.7 and cache the deps to these tests run
faster
=> Update buildkite testing

.expeditor/config.yml, .expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, chefstyle.gemspec, config/chefstyle.yml, config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
This has some important bug fixes needed by Cookstyle so it needs to get
bumped here as well.
=> Update to RuboCop 0.82 engine

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Bump to RuboCop 0.89.1

bin/chefstyle, chefstyle.gemspec, config/chefstyle.yml, lib/chefstyle.rb
=> Enable 7 more cops to simplify our code

config/disable_all.yml, config/upstream.yml, lib/chefstyle.rb, lib/chefstyle/version.rb, lib/rubocop/monkey_patches/rescue_ensure_alignment.rb, spec/rubocop/monkey_patches/rescue_ensure_alignment_spec.rb
=> Update RuboCop engine to 0.91

lib/rubocop/cop/chef/ruby/unless_defined_require.rb
Add Pastel and use the Canary with ChefUtils
=> Update classs in unless_defined_required

lib/rubocop/cop/chef/ruby/unless_defined_require.rb
=> Remove yaml from unless defined for now

.gitignore, config/chefstyle.yml, config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update to Rubocop 0.93

config/upstream.yml, lib/chefstyle/version.rb
This has a few important bug fixes for us
=> Update to RuboCop 0.93.1

config/chefstyle.yml
These are all fixed in chef and ohai.
=> Enable new cops

config/upstream.yml, lib/chefstyle/version.rb
=> Update RuboCop to 1.3.1

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update to Rubocop 1.4.1

config/upstream.yml, lib/chefstyle/version.rb
=> Update RuboCop engine to 1.4.2

Gemfile, Rakefile, lib/chefstyle/version.rb
This unblocks the dep with berkshelf and inspec
=> Update to RuboCop 1.5.2

config/upstream.yml, lib/chefstyle/version.rb
A bunch of autocorrects have been added as well as some nice bug fixes and hints when cops in configs are wrong.
=> Update to RuboCop 1.6.1

Gemfile, config/chefstyle.yml, config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update RuboCop to 1.8.1

config/upstream.yml, lib/chefstyle/version.rb
This includes my fix for how the styleguide docs URLs are generated.
=> Update RuboCop to 1.9.1

config/chefstyle.yml, lib/rubocop/cop/chef/ruby/gemspec_license.rb, spec/rubocop/cop/chef/ruby/chefspec_license_spec.rb
Make sure our gemspecs define a license
=> Add new Chef/Ruby/GemspecLicense cop

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update to RuboCop 1.10

.expeditor/verify.pipeline.yml
=> Add Ruby 3.0 testing

lib/chefstyle/version.rb
=> Update to RuboCop 1.12.1

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update RuboCop to 1.14

chefstyle.gemspec
=> Make sure the gem requires Ruby 2.5+

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
=> Update RuboCop engine to 1.18.3

lib/chefstyle/version.rb
=> Update RuboCop to 1.18.4

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
Obvious fix; these changes are the result of automation not creative thinking.
=> Update RuboCop to 1.22

config/chefstyle.yml
We should pull from secure sources at all times
=> Enable Bundler/InsecureProtocolSource cop

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
This has some nice improvements including a fix for `Style/StringLiterals` that matters to us.
=> Update RuboCop to 1.23

config/disable_all.yml, config/upstream.yml, lib/chefstyle/version.rb
Lots of bug fixes and new cops
=> Update RuboCop engine to 1.24.1
