config/chefstyle.yml

This enforces that multiline arrays/hashes should end with a trailing comma

Set Style/TrailingComma to sensible default

---

config/chefstyle.yml

cc @chef/client-maintainers
We mix single quotes and double quotes all the time in files, and it's really annoying to try and match what the rest of the file does.
There's no performance cost to just using double quotes across the board, and it makes life better.

Enable Style/StringLiterals and set it to double quotes

---

config/chefstyle.yml

I grepped the source code looking for actual usage and went through
the old ruby 1.9 pickaxe PDF and the result is that '{}' is how we
actually have written the chef source code and its what all the old
farts actually learned.
e.g.
```
% egrep -rI "%w" . | sed -e 's/.*%w/%w/' | cut -c 1-3 | sort | uniq -c | sort -rn
164 %w{
100 %w(
54 %w[
1 %w|
```
I vote the old ways are best and there's no reason to change this.
And if you go back to chef 11.0.0 its gets somewhat more lopsided towards '{}':
```
% egrep -rI "%w" . | sed -e 's/.*%w/%w/' | cut -c 1-3 | sort | uniq -c | sort -rn
120 %w{
30 %w[
23 %w(
1 %w|
```

add rule for Style/PercentLiteralDelimiters

---

config/chefstyle.yml

for some reason chefstyle doesn't complain about these, but if i run
rubocop it gets pissed about deprecated/renamed configs.
may need to make chefstyle more strict about config file parsing.

fixes for 0.37.2

---

config/chefstyle.yml
config/disable_all.yml
config/disabled.yml
config/enabled.yml
config/upstream.yml
lib/chefstyle/version.rb

also bumps the version for 0.4.0 since next step will be releasing after cleaning up ohai, etc.
closes #29

add BlockDelimiters and MultilineBlockLayout and bump engine to 0.42.0

---

config/chefstyle.yml

disable Style/SpaceInsidePercentLiteralDelimiters

---

config/chefstyle.yml

allow for separating single-line expressions (typically one liners with
anonymous functions with more than one statement, which often are
perfectly readable/idiomatic).
chef/chef PR is at https://github.com/chef/chef/pull/5543

enable style/semicolon

---

config/chefstyle.yml

Underscores in numbers are unnecessary, especially for port numbers in attributes where they are unexpected
Signed-off-by: Matt Ray <matthewhray@gmail.com>

disable Style/NumericLiterals

---

config/chefstyle.yml

the latter is fairly annoying since autofixing tends to break
code.
chef/chef#5814 merged the fixes for this.

add 3 "redundant" cops and turn off the English one

---

config/chefstyle.yml

we're dropping ruby 2.1/2.2 support everywhere (except for like
mixlib-install where i just specifically override this in that
project's .rubocop.yml file)

bump target ruby to 2.3

---

config/chefstyle.yml

the one that seems most problematic here is actually `Lint/AssignmentInCondition` where we have 71 offenses that look like they're correctly using assignment in conditionals.  e.g.:
```
until exitstatus = Process.waitpid2(pid, Process::WNOHANG)
```
and
```
if match = line.match(/^.*?:.*?: \s+(.*)/)
```

enable Security/Eval and all remaining Lint

---

config/chefstyle.yml
config/disable_all.yml
config/disabled.yml
config/enabled.yml
config/upstream.yml
lib/chefstyle/version.rb

we need to bump to at least 0.53.0 to remove the deprecation warning error message https://github.com/bbatsov/rubocop/issues/5662#issuecomment-372020867

bump rubocop to 0.54.0

---

config/chefstyle.yml

allows this layout in implicit functions:
foo(this: this, that: that, another: another,
thing: thing)

make hash alignment less annoying

---

config/chefstyle.yml

autocorrect breaks things:
https://github.com/rubocop-hq/rubocop/issues/6099

disable Style/UnneededInterpolation

---

.travis.yml
chefstyle.gemspec
lib/chefstyle/version.rb

Avoid shipping rakefile, gemfile, and the gemspec when we don't need it in the gem itself.

Slim gem and release 0.11

---

config/chefstyle.yml

rubocop-hq/rubocop#4432 and rubocop-hq/rubocop#3752 have been closed
against this cop which make it pretty annoying with false positives.
since this is a lint that complains against a hard-error from bundler
there really isn't a lot of point to this.  throwing a style error
to prevent a syntax error, where the linter will necessarily be
inaccurate due to static analysis is not adding value.

disable Bundler/DuplicatedGem

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml
.github/CODEOWNERS
config/chefstyle.yml
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This includes a large number of bug fixes and also removes the performance and rails cops.

Update the Rubocop engine to 0.72

---

config/chefstyle.yml

- format strings are rarely used
- 99% of the alerts are false positives
- there is no autofixing cop for this one

disable Style/FormatStringToken

---

Rakefile
config/chefstyle.yml

Updated rules for this engine update.

New Chefstyle Rules

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This doesn't enable any new rules, but it resolves several pages of bugfixes plus a few features I wanted to get into cookstyle. Those bugfixes will probably result in new failures popping up.

Bump rubocop to 0.75.1 for multiple bugfixes

---

lib/chefstyle.rb

Use require_relative to avoid traversing the filesystem

Use require_relative instead of require

---

config/chefstyle.yml

required for ruby 2.7
https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string

enable Lint/UriEscapeUnescape

---

config/chefstyle.yml

This has been working great in cookstyle and greatly reduces the amount of time necessary to get a project using chefstyle.

Allow chefstyle to autocorrect indentation issues

---

Gemfile
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This resolves a large number of bugs that impacted us on the Cookstyle
side and also adds support for Ruby 2.7 syntax to many cops.

Update to Rubocop 0.81.0

---

chefstyle.gemspec

We never appbundle this app so we don't need either of these.

Stop shipping the Gemfile and Gemspec in the gem

---

Gemfile
chefstyle.gemspec

Remove unused groups, but add back the gemspec which is actually used by appbundler.

Add back the Gemspec, but remove gemfile dev groups

---

config/chefstyle.yml

We're fixing the indentation of the code and not doing the comments. It
makes for some terrible to read autocorrected code.
The chef/chef fix using this is https://github.com/chef/chef/pull/9811

Make sure our comments line up with our code

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Fixes a giant pile of bugs including a few that impacted cookbooks
Adds autocorrection to a few cops including the issues with ambiguous operators that was painful in cookbooks

Update RuboCop to 0.83

---

config/chefstyle.yml
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Also enable Lint/DeprecatedOpenSSLConstant so we can catch this deprecation now.

Update RuboCop engine from 0.83 to 0.85

---

lib/chefstyle/version.rb

This includes a few useful bug fixes, but no config changes so there's
no need to vendor

Require RuboCop 0.85.1

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This adds autocorrection to several existing cops and fixes bugs that impacted cookstyle

Update Rubocop to 0.86

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This version has a whole new 1.0 API for autocorrection. None of that should impact us in any way, but it's pretty different under the hood.

Update to RuboCop 0.87.1

---

.rubocop.yml
Gemfile
Rakefile
bin/chefstyle
chefstyle.gemspec
config/chefstyle.yml
lib/chefstyle.rb
lib/chefstyle/version.rb

The encoding cop was previously disabled as it *added* the encoding comments. Now it removes them if they were setting utf-8 since that's the default on Ruby 2 and is totally pointless to set.
This also enables the frozen string literal comment cop for this repo so we can start the process of getting ready to enable that.

Enable Style/Encoding cop

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Vendor rubocop-0.88.0 upstream configuration.

---

config/chefstyle.yml
lib/rubocop/cop/chef/ruby/require_net_https.rb
spec/rubocop/cop/chef/ruby/require_net_https_spec.rb

Catch anywhere we're still doing this.

Add ChefRuby/RequireNetHttps

---

Rakefile
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Lots of improved cops in this release plus perf improvements

Update RuboCop to 0.90

---

lib/rubocop/cop/chef/ruby/unless_defined_require.rb

This is related to https://github.com/chef/chef/pull/9834 and shouldn't be merged until that PR is also merged.
Signed-off-by: Lance Albertson <lance@osuosl.org>

Add cop for chef-utils/dist requires

---

config/chefstyle.yml

Something inside rubocop enabled this rule previously even though we've
had it disabled the whole time.

Enable Lint/Syntax

---

Rakefile
config/chefstyle.yml
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb
lib/rubocop/cop/chef/ruby/gemspec_require_rubygems.rb
lib/rubocop/cop/chef/ruby/require_net_https.rb
lib/rubocop/cop/chef/ruby/ruby_27_keyword_argument_warnings.rb
lib/rubocop/cop/chef/ruby/unless_defined_require.rb
spec/rubocop/cop/chef/ruby/gemspec_require_rubygems_spec.rb
spec/rubocop/cop/chef/ruby/require_net_https_spec.rb
spec/rubocop/cop/chef/ruby/ruby_27_keyword_argument_warnings_spec.rb
spec/rubocop/cop/chef/ruby/unless_defined_require_spec.rb

Update to RuboCop 1.2

---

Gemfile
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Upgrade to RuboCop 1.3.0

---

config/chefstyle.yml

This is a common thing with empty class defs

Allow 1 line defs w/o a space between

---

config/chefstyle.yml
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Update RuboCop to 1.5.0

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

A whole bunch of autocorrect updates and bug fixes

Update to RuboCop 1.7

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

TONS of bug fixes and autocorrect improvements

Update to RuboCop 1.9

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Obvious fix; these changes are the result of automation not creative thinking.

Vendor rubocop-1.11.0 upstream configuration.

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Improves some detection and fixes a huge pile of bugs

Update RuboCop to 1.12

---

.expeditor/verify.pipeline.yml
config/chefstyle.yml
config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This release removes support for Ruby 2.4

Update to RuboCop 1.13 and remove Ruby 2.4 support

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

This includes a bunch of bug fixes that are important to pull into our projects.

Update RuboCop engine to 1.15

---

config/disable_all.yml
config/upstream.yml
lib/chefstyle/version.rb

Update RuboCop 1.15 -> 1.17

---

config/upstream.yml
lib/chefstyle/version.rb

Obvious fix; these changes are the result of automation not creative thinking.

Update to RuboCop 1.25
